services:
  postgrest:
    container_name: postgrest
    image: postgrest/postgrest
    restart: unless-stopped
    environment:
      - PGRST_DB_URI=postgres://postgres:postgres@db.dblsoft.lan:15432/cnpj_data
      - PGRST_DB_ANON_ROLE=postgres
    networks:
      - cnpj-data
  api_proxy:
    container_name: api_proxy
    image: api_proxy:latest
    restart: unless-stopped
    build:
      context: ../s/api_proxy
      dockerfile: Dockerfile
      platforms:
        - "linux/arm64"
        - "linux/amd64"
    environment:
      - NODE_ENV=production
      - ISSUER=http://iam.dblsoft.xyz/realms/apps
      - AUDIENCE=api-data
      - JWK_URI=http://iam.dblsoft.xyz/realms/apps/protocol/openid-connect/certs
      - TARGET_API=http://postgrest:3000/
      - ENABLE_AUTH=false
    ports:
      - 3001:3001
    networks:
      - cnpj-data

networks:
  cnpj-data: