apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-proxy
  template:
    metadata:
      labels:
        app: api-proxy
    spec:
      containers:
        - name: postgrest
          image: postgrest/postgrest:latest
          ports:
            - containerPort: 3000
          env:
            - name: PGRST_DB_URI
              value: postgres://company_data:company_data@192.168.2.185:5432/company_data
            - name: PGRST_DB_ANON_ROLE
              value: company_data
        - name: api-proxy
          image: registry.dblsoft.xyz/api_proxy:latest
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              value: production
            - name: ISSUER
              value: https://iam.dblsoft.xyz/realms/apps
            - name: AUDIENCE
              value: app
            - name: JWK_URI
              value: https://iam.dblsoft.xyz/realms/apps/protocol/openid-connect/certs
            - name: TARGET_API
              value: http://127.0.0.1:3000/
---
apiVersion: v1
kind: Service
metadata:
  name: api-proxy-service
spec:
  selector:
    app: api-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cnpj-data-admin
  template:
    metadata:
      labels:
        app: cnpj-data-admin
    spec:
      containers:
        - name: app-web-admin-container
          image: registry.dblsoft.xyz/app_web_admin:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: VITE_OIDC_ENDPOINT
              value: https://iam.dblsoft.xyz/
            - name: VITE_OIDC_REALM
              value: apps
            - name: VITE_OIDC_CLIENT
              value: app
            - name: VITE_API_URL
              value: http://192.168.2.201
---
apiVersion: v1
kind: Service
metadata:
  name: app-web-admin-service
spec:
  selector:
    app: cnpj-data-admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
