apiVersion: v1
kind: Namespace
metadata:
  name: cnpj-data
  labels:
    name: cnpj-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnpj-data-admin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cnpj-data-admin
  template:
    metadata:
      labels:
        app: cnpj-data-admin
    spec:
      containers:
        - name: app-web-admin-container
          image: registry.dblsoft.xyz/app_web_admin:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: VITE_OIDC_ENDPOINT
              value: https://iam.dblsoft.xyz/
            - name: VITE_OIDC_REALM
              value: apps
            - name: VITE_OIDC_CLIENT
              value: app
            - name: VITE_API_URL
              value: http://192.168.2.201
---
apiVersion: v1
kind: Service
metadata:
  name: app-web-admin-service
spec:
  selector:
    app: cnpj-data-admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
