apiVersion: v1
kind: Namespace
metadata:
  name: cnpj-data
  labels:
    name: cnpj-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-proxy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-proxy
  template:
    metadata:
      labels:
        app: api-proxy
    spec:
      containers:
        - name: postgrest
          image: postgrest/postgrest:v12.0.2
          ports:
            - containerPort: 3000
          env:
            - name: PGRST_DB_URI
              value: postgres://company_data:company_data@192.168.2.185:5432/company_data
            - name: PGRST_DB_ANON_ROLE
              value: company_data
        - name: api-proxy
          image: registry.dblsoft.xyz/api-proxy:latest
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              value: production
            - name: ISSUER
              value: https://iam.dblsoft.xyz/realms/apps
            - name: AUDIENCE
              value: app
            - name: JWK_URI
              value: https://iam.dblsoft.xyz/realms/apps/protocol/openid-connect/certs
            - name: TARGET_API
              value: http://127.0.0.1:3000/
---
apiVersion: v1
kind: Service
metadata:
  name: api-proxy-service
spec:
  selector:
    app: api-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer